version: "3.8"

services:
  sqledge:
    image: mcr.microsoft.com/azure-sql-edge
    container_name: sqledge
    environment:
      ACCEPT_EULA: "1"
      MSSQL_SA_PASSWORD: ${DB_PASSWORD}
    ports:
      - "1433:1433"

  sensor-api:
    build: ./sensor-api
    container_name: sensor-api
    environment:
      DB_SERVER: ${DB_SERVER}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      API_PORT: ${API_PORT}
    ports:
      - "${API_PORT}:80"
    depends_on:
      - sqledge

  grafana:
    image: grafana/grafana-oss:10.2.3
    container_name: grafana
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_INSTALL_PLUGINS: marcusolsson-json-datasource
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PW}
    volumes:
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - grafana-storage:/var/lib/grafana
    ports:
      - "3000:3000"
    depends_on:
      - sensor-api

volumes:
  grafana-storage:
